### ISSUE TITLE
Cannot start up exporter with Kind

### ISSUE THREAD

**Issue by vincent-pli** [sustainable-computing-io/kepler#373]
**Describe the bug**
Try `kepler` with Kind, but the exporter cannot startup, get below errors in logs:
not sure if the Kind is not in the support list.
```
[root@experimental kepler]# k -n kepler logs -f kepler-exporter-kgvdl
panic: runtime error: index out of range [16] with length 16

goroutine 1 [running]:
github.com/sustainable-computing-io/kepler/pkg/power/rapl/source.mapPackageAndCore()
	/opt/app-root/src/github.com/sustainable-computing-io/kepler/pkg/power/rapl/source/msr_util.go:88 +0x234
github.com/sustainable-computing-io/kepler/pkg/power/rapl/source.InitUnits()
	/opt/app-root/src/github.com/sustainable-computing-io/kepler/pkg/power/rapl/source/msr_util.go:147 +0x1d
github.com/sustainable-computing-io/kepler/pkg/power/rapl/source.(*PowerMSR).IsSupported(...)
	/opt/app-root/src/github.com/sustainable-computing-io/kepler/pkg/power/rapl/source/msr.go:22
github.com/sustainable-computing-io/kepler/pkg/power/rapl.init.0()
	/opt/app-root/src/github.com/sustainable-computing-io/kepler/pkg/power/rapl/power.go:53 +0xdb
```

**To Reproduce**

**Additional context**

**Comment by jichenjc** [comment]
it is 
I am guessing kind env report different data lead to code handling not well
technically it should report error or return empty map etc

assume you are using latest version?

**Comment by rootfs** [comment]
@vincent-pli 

The offending line is [here](https://github.com/sustainable-computing-io/kepler/blob/main/pkg/power/rapl/source/msr_util.go#L88)

Based on the error, it looks you have 16 cores (indexed from 0 to 15) and somehow CPU core to pkg mapping finds core 16. 

Can you get the following output?

```bash
cat /sys/devices/system/cpu/cpu*/topology/physical_package_id
```

**Comment by rootfs** [comment]
btw, MSR is turned off, oddly go build doesn't take the [hint](https://github.com/sustainable-computing-io/kepler/blob/main/pkg/power/rapl/power.go#L53)

**Comment by vincent-pli** [comment]
Checked the code and VM, it's weird...
my core number is 16 and 
`cat /sys/devices/system/cpu/cpu15/topology/physical_package_id`
get 30

@rootfs  @jichenjc

**Comment by rootfs** [comment]
that sounds a bogus physical_package_id. 

In any case, @vincent-pli do you like to post a fix? Either completely disable MSR or add protection around the slice

**Comment by marceloamaral** [comment]
The Kind cluster is probably not the problem.

All my tests were using RAPL `sysfs`, and it's interesting that you've seen problems with the msr package.

So the package is not finding the correct socket (package) ID for the CPU.

How many sockets does your system have?
What OS are you using?
Is it BareMetal or VM?

**Comment by vincent-pli** [comment]
It's a VM on the VMware vSphere, core number is 16
OS is centos 8
```
[root@experimental data-adapter]# ss -s
Total: 752
TCP:   455 (estab 151, closed 281, orphaned 0, timewait 104)

Transport Total     IP        IPv6
RAW	  1         0         1
UDP	  8         5         3
TCP	  174       171       3
INET	  183       176       7
FRAG	  0         0         0
```
@marceloamaral

**Comment by marceloamaral** [comment]
@vincent-pli Interesting, does this VM has RAPL support?
In the case you did not check it before, you could verify it using the [rapl reader](https://web.eece.maine.edu/~vweaver/projects/rapl/)

**Comment by vincent-pli** [comment]
I don't think it has the PAPL support, based on the 
`*four* ways to read RAPL results on Linux`

I noticed the kernel version is `4.18.0-408.el8.x86_64`, it that the reason? @marceloamaral

**Comment by marceloamaral** [comment]
@vincent-pli By default, RAPL is not supported on VMs
We have an issue #367 to investigate the possibilities to enable RAPL within VMs...

In any case, since RAPL is not supported, Kepler should not try to run via MSR.
@rootfs So, this is a bug that we need to fix.

**Comment by rootfs** [comment]
@marceloamaral sounds good, let's disable MSR when RAPLs not available.

**Comment by vincent-pli** [comment]
@marceloamaral @rootfs 
I checked the code again, I think the VM has the MSR support at least, since I can find `/dev/cpu/%d/msr`.
and for the problem of `physical_package_id`, here is the explained from official：
```
physical package id of cpuX. Typically corresponds to a physical socket number, 
but the actual value is architecture and platform dependent.
```

In my case, the content of 
`/sys/devices/system/cpu/cpu%d/topology/physical_package_id` is  2*${cpu_num}, that's why it crashed (out of index).

So I wonder if it's just a code problem, the content of `physical_package_id` is make sense sometimes.
I modified the original code:  #400 
feel free to close the PR, thanks

**Comment by vincent-pli** [comment]
BTW, after modification, the log like this:
```
[root@experimental kepler]# k -n kepler logs -f kepler-exporter-jkg2z
I1116 05:44:41.353773       1 exporter.go:81] Kepler running on version: v0.3-151-g2789a22-dirty
I1116 05:44:41.353888       1 config.go:89] using gCgroup ID in the BPF program: true
I1116 05:44:41.353943       1 config.go:90] kernel version: 4.18
I1116 05:44:41.354033       1 exporter.go:106] Initializing the Model Server
I1116 05:44:41.519725       1 slice_handler.go:189] Not able to find any valid .scope file in /sys/fs/cgroup/cpu, this likely cause all cgroup metrics to be 0
I1116 05:44:41.558784       1 exporter.go:114] Initializing the GPU collector
perf_event_open: No such file or directory
I1116 05:44:45.118640       1 bcc_attacher.go:90] failed to attach perf event cache_miss: failed to open bpf perf event: no such file or directory
perf_event_open: No such file or directory
I1116 05:44:45.118786       1 bcc_attacher.go:90] failed to attach perf event cpu_cycles: failed to open bpf perf event: no such file or directory
perf_event_open: No such file or directory
I1116 05:44:45.118872       1 bcc_attacher.go:90] failed to attach perf event cpu_instr: failed to open bpf perf event: no such file or directory
I1116 05:44:45.118886       1 bcc_attacher.go:131] Successfully load eBPF module with option: [-DNUM_CPUS=16 -DCPU_FREQ]
I1116 05:44:45.141558       1 exporter.go:152] Started Kepler in 3.787845582s
```

and no data collected in the Grafana. so my VM still cannot saitified the requirement?

**Comment by marceloamaral** [comment]
@vincent-pli that is very interesting that your VM has MSR.
Can you see energy consumption values? Did you try the rapl reader code?

Regarding the no data, can you run Kepler with higher verbosity (-v=5)?

In your logs we can see that the VM does not have support for hardware counters. The hardware counters are typically enabled when the VM is using CPU passthrough. 
Currently Kepler depends on the hardware counters to identify new containers, see issue #364. But the already running containers should be identified during the initialization. That is, you should see some data.

**Comment by vincent-pli** [comment]
Changed the log level, get tons of:
```
128 I1121 06:56:51.168738       1 container_metric.go:194] cannot extract: block_devices_used
  129 I1121 06:56:51.168744       1 container_metric.go:194] cannot extract: block_devices_used
  130 I1121 06:56:51.168750       1 container_metric.go:194] cannot extract: block_devices_used
  131 I1121 06:56:51.168759       1 container_metric.go:194] cannot extract: block_devices_used
  132 I1121 06:56:51.168771       1 container_metric.go:194] cannot extract: block_devices_used
  133 I1121 06:56:51.168778       1 container_metric.go:194] cannot extract: block_devices_used
  134 I1121 06:56:51.168888       1 metric_collector.go:132] energy from pod (0 processes): name: alertmanager-main-0 namespace: monitoring
  135         cgrouppid: 0 pid: [] comm:
  136         ePkg (mJ): 0 (0) (eCore: 0 (0) eDram: 0 (0) eUncore: 0 (0)) eGPU (mJ): 0 (0) eOther (mJ): 0 (0)
  137         eDyn (mJ): 0 (0)
  138         avgFreq: 0.00
  139         CPUTime:  0 (0)
  140         counters: map[cache_miss:0 (0) cpu_cycles:0 (0) cpu_instr:0 (0)]
  141         cgroupfs: map[]
  142         kubelets: map[container_cpu_usage_seconds_total:0 (119) container_memory_working_set_bytes:0 (24412160)]
  143
  144 I1121 06:56:51.168972       1 metric_collector.go:132] energy from pod (0 processes): name: alertmanager-main-1 namespace: monitoring
  145         cgrouppid: 0 pid: [] comm:
  146         ePkg (mJ): 0 (0) (eCore: 0 (0) eDram: 0 (0) eUncore: 0 (0)) eGPU (mJ): 0 (0) eOther (mJ): 0 (0)
  147         eDyn (mJ): 0 (0)
  148         avgFreq: 0.00
  149         CPUTime:  0 (0)
  150         counters: map[cache_miss:0 (0) cpu_cycles:0 (0) cpu_instr:0 (0)]
  151         cgroupfs: map[]
  152         kubelets: map[container_cpu_usage_seconds_total:0 (1985) container_memory_working_set_bytes:0 (31539200)]
  153
  154 I1121 06:56:51.169002       1 metric_collector.go:132] energy from pod (0 processes): name: prometheus-operator-854d57765-6fwhz namespace: monitoring
  155         cgrouppid: 0 pid: [] comm:
  156         ePkg (mJ): 0 (0) (eCore: 0 (0) eDram: 0 (0) eUncore: 0 (0)) eGPU (mJ): 0 (0) eOther (mJ): 0 (0)
  157         eDyn (mJ): 0 (0)
  158         avgFreq: 0.00
  159         CPUTime:  0 (0)
  160         counters: map[cache_miss:0 (0) cpu_cycles:0 (0) cpu_instr:0 (0)]
  161         cgroupfs: map[]
  162         kubelets: map[container_cpu_usage_seconds_total:0 (92) container_memory_working_set_bytes:0 (23228416)]
```
@marceloamaral

**Comment by rootfs** [comment]
@vincent-pli can you post the beginning of the log?

**Comment by vincent-pli** [comment]
@rootfs @marceloamaral 
I'd like to leverage kepler as a key component in our approach, so shoud I find bare metal or vm with some specific requirement to make it works?
I'm not a expert for linux kernal, so I need some guide, thanks

**Comment by rootfs** [comment]
@vincent-pli cgroupfs metrics is empty, this causes problem, can you check if your node is running on cgroup v2? 
```
Available cgroup metrics from cgroup: []
```

**Comment by vincent-pli** [comment]
Seems, it has v2 installed @rootfs 
```
[root@experimental ~]# grep cgroup /proc/filesystems
nodev	cgroup
nodev	cgroup2
```

**Comment by vincent-pli** [comment]
Also, I try rapl reader, and get this:
```
[root@experimental rapl-read]# ./rapl-read

RAPL read -- use -s for sysfs, -p for perf_event, -m for msr

Found Sandybridge-EP Processor type
	0 (0), 1 (2), 2 (4), 3 (6), 4 (8), 5 (10), 6 (12), 7 (14)
	8 (16), 9 (18), 10 (20), 11 (22), 12 (24), 13 (26), 14 (28), 15 (30)

	Detected 16 cores in 8 packages


Trying sysfs powercap interface to gather results

	Could not open /sys/class/powercap/intel-rapl/intel-rapl:0/name

Trying /dev/msr interface to gather results

	Listing paramaters for package #0
		Power units = 1.000W
		CPU Energy units = 1.00000000J
		DRAM Energy units = 1.00000000J
		Time units = 1.00000000s

		Package thermal spec: 0.000W
		Package minimum power: 0.000W
		Package maximum power: 0.000W
		Package maximum time window: 0.000000s
		Package power limits are unlocked
		Package power limit #1: 0.000W for 0.000000s (disabled, not_clamped)
		Package power limit #2: 0.000W for 0.000000s (disabled, not_clamped)
	Accumulated Package Throttled Time : 0.000000s
	PowerPlane0 (core) Accumulated Throttled Time : 0.000000s
	PowerPlane0 (core) for core 0 policy: 0
	Listing paramaters for package #1
rdmsr:open: No such file or directory
Trying to open /dev/cpu/-1/msr
```
@rootfs  @marceloamaral

**Comment by sunya-ch** [comment]
Not sure whether this would help but I also see the issue that init() function in the power module is not called and no node energy can be read.
I committed a change to my local to solve the issue but have no time to push as a PR yet. You may check the following commit.

https://github.com/sunya-ch/kepler/commit/2b7f74d4c656297cee1c45dc10db6cb87c9d9f33#diff-c3d1be9255e1327664e762d9a3b15122141371972ec7ae315074abb55b2909f1

**Comment by jichenjc** [comment]
@vincent-pli did you use latest version ? Kepler running on version: v0.3-151-g2789a22-dirty didn't know whether it's latest ..

https://github.com/sustainable-computing-io/kepler/issues/352#issuecomment-1309998942
I met this issue before and fixed this by running RHEL version(originally use Ubutu has this problem)
so switch to RHEL and update the PR in the issue I pasted above, the cgroup metrics show up

**Comment by vincent-pli** [comment]
@jichenjc I used the latest source code to build a arch amd64 binary, seems the cgroup metrics is back but seems still no luck, no data in the Grafana:
```
                                                                                                                                                                                                  573,1         Bot
I1122 02:19:18.352160       1 exporter.go:149] Kepler running on version: v0.3-187-g753e014
I1122 02:19:18.352308       1 config.go:124] using gCgroup ID in the BPF program: true
I1122 02:19:18.352354       1 config.go:125] kernel version: 4.18
I1122 02:19:18.352658       1 slice_handler.go:145] InitSliceHandler: &{map[] /sys/fs/cgroup/cpu/system.slice /sys/fs/cgroup/memory/system.slice /sys/fs/cgroup/blkio/system.slice}
I1122 02:19:18.352721       1 bcc_attacher.go:143] hardeware counter metr true
I1122 02:19:18.354536       1 slice_handler.go:179] Not able to find any valid .scope file in /sys/fs/cgroup/cpu/system.slice, this likely cause all cgroup metrics to be 0
I1122 02:19:18.461827       1 bcc_attacher.go:143] hardeware counter metr true
I1122 02:19:18.461884       1 utils.go:38] Available counter metrics: [cache_miss cpu_cycles cpu_instr]
I1122 02:19:18.461917       1 utils.go:39] Available cgroup metrics from cgroup: [cgroupfs_tcp_memory_usage_bytes cgroupfs_cpu_usage_us cgroupfs_system_cpu_usage_us cgroupfs_user_cpu_usage_us cgroupfs_memory_usage_bytes cgroupfs_kernel_memory_usage_bytes]
I1122 02:19:18.461939       1 utils.go:40] Available cgroup metrics from kubelet: [container_cpu_usage_seconds_total container_memory_working_set_bytes]
I1122 02:19:18.461992       1 utils.go:41] Available I/O metrics: [bytes_read bytes_writes]
I1122 02:19:18.462014       1 lr.go:167] LR Model (AbsModelWeight): no config
I1122 02:19:18.462029       1 model.go:76] Model AbsModelWeight initiated (false)
I1122 02:19:18.462075       1 lr.go:167] LR Model (AbsComponentModelWeight): no config
I1122 02:19:18.462091       1 model.go:76] Model AbsComponentModelWeight initiated (false)
I1122 02:19:18.462104       1 lr.go:167] LR Model (DynModelWeight): no config
I1122 02:19:18.462117       1 model.go:76] Model DynModelWeight initiated (false)
I1122 02:19:18.462129       1 lr.go:158] getWeightFromServer failed, using InitModelURL:https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/DynComponentModelWeight/CgroupOnly/ScikitMixed/ScikitMixed.json to load
I1122 02:19:18.620216       1 lr.go:164] LR Model (DynComponentModelWeight) Weight: map[dram:{{5318.157697416588 map[] map[bytes_read:{0 0 0} bytes_writes:{7.841098405047592e+16 1.0766045667937836e+36 0} cgroupfs_cpu_usage_us:{1.0056068008622782e+07 1.40009411083803e+14 1446.1905640274801} cgroupfs_memory_usage_bytes:{1.944592404177567e+18 1.5694324114250333e+37 140.278995536714} cgroupfs_system_cpu_usage_us:{354378.9946563031 1.3693308434958022e+11 2808.988723422464} cgroupfs_user_cpu_usage_us:{1.0056068008622782e+07 1.40009411083803e+14 0}]}} pkg:{{5326.461712554309 map[] map[bytes_read:{0 0 0} bytes_writes:{7.841098405047592e+16 1.0766045667937836e+36 0} cgroupfs_cpu_usage_us:{1.0056068008622782e+07 1.40009411083803e+14 0} cgroupfs_memory_usage_bytes:{1.944592404177567e+18 1.5694324114250333e+37 149.97387537247224} cgroupfs_system_cpu_usage_us:{354378.9946563031 1.3693308434958022e+11 2814.0186059477487} cgroupfs_user_cpu_usage_us:{1.0056068008622782e+07 1.40009411083803e+14 1452.6093109776657}]}}]
I1122 02:19:18.620367       1 model.go:76] Model DynComponentModelWeight initiated (true)
I1122 02:19:18.620388       1 exporter.go:164] Initializing the GPU collector
perf_event_open: No such file or directory
I1122 02:19:22.660711       1 bcc_attacher.go:90] failed to attach perf event cpu_cycles: failed to open bpf perf event: no such file or directory
perf_event_open: No such file or directory
I1122 02:19:22.660825       1 bcc_attacher.go:90] failed to attach perf event cpu_instr: failed to open bpf perf event: no such file or directory
perf_event_open: No such file or directory
I1122 02:19:22.661001       1 bcc_attacher.go:90] failed to attach perf event cache_miss: failed to open bpf perf event: no such file or directory
I1122 02:19:22.661019       1 bcc_attacher.go:131] Successfully load eBPF module with option: [-DNUM_CPUS=16 -DCPU_FREQ]
I1122 02:19:22.696750       1 node_energy_collector.go:57] No nodeComponentsEnergy found, node components energy metrics is not exposed
I1122 02:19:22.697716       1 exporter.go:202] Started Kepler in 4.345610617s
I1122 02:19:23.047463       1 container_metric.go:194] cannot extract: block_devices_used
I1122 02:19:23.047587       1 container_metric.go:194] cannot extract: block_devices_used
I1122 02:19:23.047634       1 container_metric.go:194] cannot extract: block_devices_used
I1122 02:19:23.047701       1 container_metric.go:194] cannot extract: block_devices_used
```
and 
```
I1122 02:19:25.869601       1 metric_collector.go:132] energy from pod (0 processes): name: alertmanager-main-2 namespace: monitoring
        cgrouppid: 0 pid: [] comm:
        ePkg (mJ): 1323 (1323) (eCore: 1323 (1323) eDram: 1330 (1330) eUncore: 0 (0)) eGPU (mJ): 0 (0) eOther (mJ): 0 (0)
        eDyn (mJ): 0 (0)
        avgFreq: 0.00
        CPUTime:  0 (0)
        counters: map[cache_miss:0 (0) cpu_cycles:0 (0) cpu_instr:0 (0)]
        cgroupfs: map[cgroupfs_cpu_usage_us:0 (0) cgroupfs_kernel_memory_usage_bytes:0 (0) cgroupfs_memory_usage_bytes:0 (0) cgroupfs_system_cpu_usage_us:0 (0) cgroupfs_tcp_memory_usage_bytes:0 (0) cgroupfs_user_cpu_usage_us:0 (0)]
        kubelets: map[container_cpu_usage_seconds_total:0 (2104) container_memory_working_set_bytes:0 (32645120)]

I1122 02:19:25.869688       1 metric_collector.go:132] energy from pod (0 processes): name: alertmanager-main-1 namespace: monitoring
        cgrouppid: 0 pid: [] comm:
        ePkg (mJ): 1323 (1323) (eCore: 1323 (1323) eDram: 1330 (1330) eUncore: 0 (0)) eGPU (mJ): 0 (0) eOther (mJ): 0 (0)
        eDyn (mJ): 0 (0)
        avgFreq: 0.00
        CPUTime:  0 (0)
        counters: map[cache_miss:0 (0) cpu_cycles:0 (0) cpu_instr:0 (0)]
        cgroupfs: map[cgroupfs_cpu_usage_us:0 (0) cgroupfs_kernel_memory_usage_bytes:0 (0) cgroupfs_memory_usage_bytes:0 (0) cgroupfs_system_cpu_usage_us:0 (0) cgroupfs_tcp_memory_usage_bytes:0 (0) cgroupfs_user_cpu_usage_us:0 (0)]
        kubelets: map[container_cpu_usage_seconds_total:0 (135) container_memory_working_set_bytes:0 (22536192)]
```

BTW, do we need to pick different version based on the os, I mean adopt RHEL for rhel mechaine?

and I will test @sunya-ch 's solusion, thanks

**Comment by jichenjc** [comment]
>>>Available cgroup metrics from cgroup: [cgroupfs_tcp_memory_usage_bytes cgroupfs_cpu_usage_us cgroupfs_system_cpu_usage_us cgroupfs_user_cpu_usage_us cgroupfs_memory_usage_bytes cgroupfs_kernel_memory_usage_bytes]

you are step further, this got fixed compare to previous 

>>>I1122 02:19:22.696750       1 node_energy_collector.go:57] No nodeComponentsEnergy found, node components energy metrics is not exposed

I met this so I added this log, I think you can check why it's reported, I believe it's related to model server or something

**Comment by rootfs** [comment]
@vincent-pli that's good news! Do you see kepler metrics in prometheus? Which version of grafana you use? Is this [dashboard](https://github.com/sustainable-computing-io/kepler/blob/main/grafana-dashboards/Kepler-Exporter.json) working?

**Comment by vincent-pli** [comment]
@rootfs No data so far, I try to dig into code to figure out the issue.
<img width="651" alt="图片" src="https://user-images.githubusercontent.com/8669744/203445520-6edf8793-52fc-4220-b529-3cbf7667d143.png">

**Comment by vincent-pli** [comment]
Finally, I get the grafana dashboard, thanks everyone @jichenjc @rootfs @marceloamaral 
So, donot use **KinD**, the `kubeadmin` setup cluster works
